version: "3.1"

services:
  mailhog:
    image: "mailhog/mailhog:latest"
    container_name: arkable_mailhog
    ports:
      - "8025:8025"
    networks:
      - arkable_network

  db:
    image: "mysql:8.0"
    container_name: arkable_db
    working_dir: /application
    volumes:
      - "arkable_mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=arkable
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    networks:
      - arkable_network

  api:
    image: "nginx:alpine"
    container_name: arkable_api
    working_dir: /application
    volumes:
      - "./packages/api:/application"
      - "./.docker/api/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "3001:80"
    networks:
      - arkable_network
    depends_on:
      - db
      - mailhog
      - php-fpm

  php-fpm:
    build: .docker/api/php-fpm
    working_dir: /application
    volumes:
      - "./packages/api:/application"
      - "./.docker/api/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini"
    networks:
      - arkable_network

  redis:
    image: redis:6.2
    ports:
      - 6379:6379
    volumes:
      - arkable_redis:/data
    networks:
      - arkable_network
    depends_on:
      - api

networks:
  arkable_network:
    driver: bridge

volumes:
  arkable_redis:
    driver: local
  arkable_mysql:
    driver: local
