version: "3.1"

services:
  mailhog:
    image: "mailhog/mailhog:latest"
    container_name: arkable_mailhog
    ports:
      - "8025:8025"
    networks:
      - arkable_network

  app_db:
    image: "mysql:8.0"
    container_name: arkable_db
    working_dir: /application
    volumes:
      - ".:/application"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=password
    ports:
      - "9002:3306"
    networks:
      - arkable_network

  client-app:
    container_name: client_app
    working_dir: /application
    build: ./packages/client
    ports:
      - "3000:3000"
    volumes:
      - "./packages/client:/application"
    networks:
      - arkable_network

  webserver:
    image: "nginx:alpine"
    container_name: arkable_webserver
    working_dir: /application
    volumes:
      - "./packages/api:/application"
      - "./.docker/api/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
    networks:
      - arkable_network
    depends_on:
      - app_db
      - mailhog

  php-fpm:
    build: .docker/api/php-fpm
    container_name: arkable_php
    working_dir: /application
    volumes:
      - ".:/application"
      - "./.docker/api/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini"
    networks:
      - arkable_network
    depends_on:
      - webserver

networks:
  arkable_network:
    driver: bridge
